AndcultureCode/AndcultureCode.JavaScript.Core

src/utilities/service-utils.ts

Fixes #17 
Just needed to update an import path from the last PR I had merged in. Wondering if there's a better way we can go about verifying our imports/exports are in order before publishing 😅

Update CollectionUtils import to be relative so it will be correctly resolved in the transpiled JS

---

src/utilities/browser-utils.test.ts
src/utilities/browser-utils.ts

add BrowserUtils.isIE() method

---

src/constants/email-constants.ts
src/index.ts
src/interfaces/scroll-options.ts
src/utilities/collection-utils.test.ts
src/utilities/collection-utils.ts
src/utilities/scroll-utils.test.ts
src/utilities/scroll-utils.ts
src/utilities/string-utils.test.ts
src/utilities/string-utils.ts

Port ScrollUtils, CollectionUtils#removeElementAt and StringUtils#join

---

src/index.ts
src/interfaces/role.ts
src/interfaces/user.ts
src/types/constructor.ts
src/utilities/record-utils.test.ts
src/utilities/record-utils.ts

Add Interfaces for Role and User; Add Constructor type; Add RecordUtils

---

src/utilities/core-utils.ts

add _.merge to CoreUtils export

---

src/utilities/collection-utils.test.ts
src/utilities/collection-utils.ts

Added tests for collection-utils methods replaceelementAt and length

---

src/enumerations/anchor-target-types.ts
src/enumerations/unit-of-time.ts

#37 #39 Port unit of time enum and anchor target types enum

Added Unit of time enum

---

tsconfig.json

The project built and the tests passed. #31

Removed base url from tsconfig file

---

src/tests/factories/factory-type.ts
src/tests/factories/index.ts
src/tests/factories/result-error-record-factory.ts
src/tests/factories/result-record-factory.ts
src/types/do-try-types.ts
src/utilities/do-try.test.ts
src/utilities/do-try.ts
src/utilities/polyfill-utils.ts

add typescript implementation of Do.try pattern

---

src/view-models/result-record.test.ts
src/view-models/result-record.ts

Add ResultRecord#doesNotHaveErrors and ResultRecord#getErrorMessageFor

---

src/utilities/core-utils.ts
src/utilities/do-try.test.ts
src/utilities/do-try.ts

fix race condition between catch and finally in do-try.ts

---

package.json

Move @types/lodash to production dependencies

---

src/utilities/service-utils.test.ts

Added additional unit test in ServiceUtils for the mapAxiosResponse function to increase test coverage to 100%.

---

src/interfaces/service-response.ts
src/utilities/do-try.test.ts
src/utilities/service-utils.test.ts
src/utilities/service-utils.ts

update ServiceUtils.mapPagedAxiosResponse to keep empty arrays intact

---

.vscode/settings.json
src/utilities/scroll-utils.test.ts
src/utilities/scroll-utils.ts

Add tests for scroll utils

---

.gitignore
src/utilities/core-utils.test.ts

Write tests for CoreUtils

---

.gitignore
src/utilities/core-utils.test.ts

Backfill tests for sleepSync

---

src/utilities/collection-utils.test.ts
src/utilities/collection-utils.ts

implement CollectionUtils.sortByString

---

src/utilities/collection-utils.test.ts
src/utilities/collection-utils.ts

Added lodash intersection and intersectionWith to CollectionUtils

---

src/utilities/scroll-utils.test.ts

Refactored some tests and added some more tests to improve code coverage.

Added tests to increase coverage

---

package.json

Issue #74 

---

src/index.ts

export BrowserUtils from index.ts

Export BrowserUtils from index.ts

---

src/utilities/collection-utils.ts
src/utilities/core-utils.ts
src/utilities/string-utils.ts

Port lodash methods to private functions. Issue #69

---

src/utilities/collection-utils.test.ts
src/utilities/collection-utils.ts
src/utilities/string-utils.ts

Add type guards 

---

src/utilities/string-utils.ts

Fixed string being evaluated as never type in typescript typeguard

---

dependency-externals.json
package-lock.json
package.json
src/utilities/localization-utils.test.ts
src/utilities/localization-utils.ts
src/utilities/string-utils.test.ts
src/utilities/string-utils.ts
test-global-distribution.html

Resolves #12 Add abstraction of browser-based language detection to localization utils 
- Might be a slight decrease but trying to be pragmatic about it. We can backfill later.

i18next browser detection

---

README.md
src/enumerations/http-header.ts
src/index.ts
src/interfaces/localization-init-options.ts
src/types/constructor.ts
src/utilities/localization-utils.ts

Fixes #102 Update README with section on internationalization
Fixes #89 Add 'Cache-Control' HttpHeader enum
Fixes #99 Move + export LocalizationInitOptions interface from LocalizationUtils
Fixes #76 Update custom Constructor type to better align with generic constructor from TS Handbook 
Looks like the `sourcerer.io` links were pointing to the JS testing repo, but even updating the references still doesn't seem to make the images render. @wintondeshong might need your assistance on that
- [-] Manually tested
- [-] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Internationalization section in readme + small misc. issues

---

src/utilities/network-information-utils.test.ts
src/utilities/network-information-utils.ts

Fixes issue #123 
- N/A Documentation updated (readme, docs, comments, etc.)
- N/A Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Add check for undefined window and navigator as well as tests

---

src/utilities/network-information-utils.test.ts
src/utilities/network-information-utils.ts

re-addresses issue #123 
- n/a Documentation updated (readme, docs, comments, etc.)
- n/a Localization: No hard-coded error messages in code files (_minimally_ in string constants)

handle undefined window in network connection utilities

---

src/utilities/collection-utils.test.ts
src/utilities/collection-utils.ts

Addresses issue #127
- n/a Documentation updated (readme, docs, comments, etc.)
- n/a Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Add typed nullable collection option to isEmpty, hasValues, and isNotEmpty functions
